### PR TITLE
Issue/trim error

### PR DESCRIPTION
**Pull request by kpverint**
PHP_CodeSniffer returns null which results in errors.

### CODE REVIEW

**Comment by jrfnl** [comment]
@kpverint Thank you for trying to make WPCS better.

I think I see what you are trying to do here. Let's first define the problem you are trying to solve:

>  When running WPCS on PHP 8.1, you are seeing deprecation notices for passing `null` as a parameter to a function where that parameter is not nullable.

Correct ?

If you look at the _current_ state of the `develop` branch, you will see that those issues have already been fixed in #1984 and #1985.

If looks like you didn't update your dev clone of WPCS before creating this PR, which also explains the file conflicts which GH shows at the bottom of this page.

Suggest: close.

**Comment by kpverint** [comment]
That's right. Thanks! :) Closing.

**Comment by WraithKenny** [comment]
Any news when you will actually publish the fixes?

**Comment by jrfnl** [comment]
When the release is ready.

**Comment by WraithKenny** [comment]
Cool, I'll just keep downgrading my computer's PHP version since 11 months wasn't enough time.

**Comment by jrfnl** [comment]
@WraithKenny Or you could start contributing instead of bashing people who actually do the work

**Comment by WraithKenny** [comment]
> @WraithKenny Or you could start contributing instead of bashing people who actually do the work

It's 2 days from being fixed, but unpublished, for exactly one year. 

"...people who actually do the work." Where? What work?

**Pull request closed without merging**
