### PR TITLE
Release WordPressCS 3.0.0

### LINKED ISSUE #1877: WordPress CS 3.0.0 planning & roadmap
Work on WordPressCS 3.0.0 will start in the near future. @GaryJones, @dingo-d and me have recently had a call to discuss what we envision for WPCS 3.0.0.

This issue is intended to keep track of what needs to be done, as well as give openness about the changes envisioned for WPCS 3.0.0.

Milestone: https://github.com/WordPress/WordPress-Coding-Standards/milestone/25

Planning:
* Ready when it's ready.
* Most of the initial PRs are tentatively expected in the ~~second half of April/beginning of May (2020)~~ July 2020.
* There will be at least one release candidate before the actual release of WPCS 3.0.0.

Environment changes:
* The minimum PHPCS requirement will go up to - at least - PHPCS 3.5.0.
* WPCS will get two (three) new dependencies:
    - [PHPCSUtils](https://github.com/PHPCSStandards/PHPCSUtils) - a set of utility functions and other helpers for sniff writers
    - [PHPCSExtra](https://github.com/PHPCSStandards/PHPCSExtra) - a set of generic sniffs
    - The [DealerDirect Composer PHPCS plugin](https://github.com/Dealerdirect/phpcodesniffer-composer-installer) - this is a dependency of the above two packages, so we will automatically benefit from it.
* The installation instructions will change.
    - A Composer based project/global install will be the recommended and only supported manner of installation.
    - Stand-alone installation from a downloaded zip file, using a git clone or using `composer create-project` will still be possible, but no support will be given for those installations.

Note: PHPCSUtils and PHPCSExtra both are on 1.0.0-alphaX releases at the time of writing this.
The first stable `1.0.0` for both will be tagged before the first WPCS 3.0.0 RC will be (pre-)released.

Roadmap / what needs to be done:
- [x] Update the environment files (`composer.json`, `.travis.yml` etc) to allow the changes to be made. - PR #1905
- [x] Remove all previously deprecated code - #1583, #1819 - PRs #1908, #1909
- [x] Remove all sniffs which can be replaced by upstream sniffs now the minimum PHPCS version has been upped (if any) and add the PHPCS native sniff to the ruleset(s) instead. - PR #1910
- [x] Remove all sniffs which can be replaced by sniffs in the PHPCSExtra standard and add the PHPCSExtra sniff to the ruleset(s) instead. - PR #1911, #1912, #1919, #1920 (more to come)
- [x] Remove all WPCS native utility methods which can be replaced by utility methods from PHPCSUtils and adjust the function calls to these methods in individual sniffs. Part 1: PR #1922, Part 2: PR #1926
- [x] Review every individual sniff for opportunities to simplify the code and/or fix "modern PHP" bugs by using utilities from PHPCSUtils.
    Where applicable, add extra unit tests to the sniff to demonstrate bugs fixed and safeguard this for the future.
    **_See the checklist in the comment below for status_**
- [ ] Once available, switch over to using the Class/Function/FunctionParam abstracts from PHPCSUtils for all sniffs using the WPCS native abstracts for these type of sniffs. (expected partially in PHPCSUtils alpha 3, partially in alpha 4).
- [ ] Once all sniffs using a particular type of WPCS native abstract sniff have been switched over, remove the WPCS native version of that abstract sniff.
- [x] Of the remaining utility methods/properties in the WPCS native `Sniff` class: aside from generically useful methods, move most methods and properties to traits which target something specific. Also see #1465 (@jrfnl)
- [x] If any WPCS sniffs extend another sniff, while the other sniff is also included in one of the WPCS rulesets, split the logic being re-used off into a trait and let the sniffs use the trait, instead of one sniff extending another as this is known to be buggy with the PHPCS autoloader.
- [x] Go through the [Make blog post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) and find relevant sniffs to add. (@jrfnl)
- [x] For those things in the Make blog post for which there are no existing sniffs in either PHPCS itself or PHPCSExtra, open an issue to create this sniff.
    Generically usable sniffs should be added to PHPCSExtra, WP or WPCS specific sniffs should be added to WPCS itself.
    Note: these do not all need to be addressed in WPCS 3.0.0. Additional sniffs can be added in minors, so some issues may be left to address later.
- [x] Go through the 3.0.0 milestone and address what else needs addressing.
- [ ] Go through the open issues to see if there are any issues which can now be more easily addressed with the utilities from PHPCSUtils and either send in a PR or milestone the issue for a later 3.x release.
- [x] Go through the open PRs, especially the ones which have been abandoned, and either update them to make them mergable if the author is no longer responding or close them.
- [x] Review the rulesets for any other sniffs replacements/tweaks which can/should be made.
- [x] Update the README and the CONTRIBUTING files for the new reality.
- [x] Write an "Upgrade Guide" for external standards which use(d) the utilities in WPCS to be added to the wiki.
- [x] Create the changelog ;-)

I've tried to be complete here, but please feel free to leave comments about anything I've forgotten in this list ;-)

### PR DESCRIPTION
**Pull request by jrfnl**
:warning: **DO NOT MERGE (YET)** :warning:

**Please **do** add approvals if you agree as otherwise we won't be able to release.**

PR for tracking changes for the 3.0.0 release. Target release date: **Monday August 21, 2023**.

### General

- [x] Verify, and if necessary, update the allowed version ranges for various dependencies in the `composer.json` - _N/A_
- [x] PHPCS: check if there have been [releases][phpcs-releases] since the last WordPressCS release and check through the changelog to see if there is anything WordPressCS could take advantage of - _N/A_
- [x] PHPCSUtils: check if there have been [releases][phpcsutils-releases] since the last WordPressCS release and update WordPressCS code to take advantage of any new utilities - _N/A_
- [x] PHPCSExtra: check if there have been [releases][phpcsextra-releases] since the last WordPressCS release and check through the changelog to see if there is anything WordPressCS could take advantage of - _N/A_
- [x] Check if the minimum WP version property needs updating in `MinimumWPVersionTrait::$default_minimum_wp_version` and if so, action it - PR #2321
- [x] Check if any of the list based sniffs need updating and if so, action it.
    :pencil2: Make sure the "last updated" annotation in the docblocks for these lists has also been updated!
    List based sniffs:
    - [x] `WordPress.WP.ClassNameCase` - PR #2317
    - [x] `WordPress.WP.DeprecatedClasses` - PR #2318
    - [x] `WordPress.WP.DeprecatedFunctions` - PR #2319
    - [x] `WordPress.WP.DeprecatedParameters` - PR #2320
    - [x] `WordPress.WP.DeprecatedParameterValues` - PR #2174 (no further update was needed)
- [x] Check if any of the other lists containing information about WP Core need updating and if so, action it.
    - [x] `$allowed_core_constants` in `WordPress.NamingConventions.PrefixAllGlobals` - PR #2315
    - [x] `$pluggable_functions` in `WordPress.NamingConventions.PrefixAllGlobals` - PR #2286
    - [x] `$pluggable_classes` in `WordPress.NamingConventions.PrefixAllGlobals` - PR #2286
    - [x] `$target_functions` in `WordPress.Security.PluginMenuSlug` - _N/A_
    - [x] `$reserved_names` in `WordPress.NamingConventions.ValidPostTypeSlug` - PR #2316
    - [x] `$wp_time_constants` in `WordPress.WP.CronInterval` - _N/A_
    - [x] `$known_test_classes` in `IsUnitTestTrait` - PR #2050
    - [ ] ...etc...

### Release prep

- [x] Add changelog for the release - PR #2368
    :pencil2: Remember to add a release link at the bottom!
- [x] Update `README` (if applicable) - PR #2367
- [x] Update wiki (new customizable properties etc.) (if applicable) - tracked in #1917

### Release

- [ ] Merge this PR.
- [ ] Make sure all CI builds are green.
- [ ] Tag and create a release against `main` (careful, GH defaults to `develop`!) & copy & paste the changelog to it.
    :pencil2: Check if anything from the link collection at the bottom of the changelog needs to be copied in!
- [ ] Make sure all CI builds are green.
- [ ] Close the milestone.
- [ ] Open a new milestone for the next release.
- [ ] If any open PRs/issues which were milestoned for this release did not make it into the release, update their milestone.
- [ ] Fast-forward `develop` to be equal to `main`.

### After release

- [ ] Open a Trac ticket for WordPress Core to update. - patch has been prepared

### Publicize

- [ ] [Major releases only] Publish post about the release on Make WordPress. - post is ready to go
- [ ] Tweet, toot, etc about the release.
- [ ] Post about it in Slack.
- [ ] Submit for ["Month in WordPress"][month-in-wp].

Closes #1877

[phpcs-releases]:      https://github.com/squizlabs/PHP_CodeSniffer/releases
[phpcsutils-releases]: https://github.com/PHPCSStandards/PHPCSUtils/releases
[phpcsextra-releases]: https://github.com/PHPCSStandards/PHPCSExtra/releases
[month-in-wp]:         https://make.wordpress.org/community/month-in-wordpress-submissions/

### CODE REVIEW

**Review by GaryJones — APPROVED** [review]
This is the culmination of an unbelievable amount of work by one volunteer. It's taken 3 years, but the changes made in relation to WordPressCS also help the wider PHP community as well.

It sets up the WordPress community for checking coding standards (including "modern" code that WordPress Core itself can't use yet) with a high degree of confidence in avoiding false positives and false negatives. 

Congratulations Juliette! 👏🏻 🙇🏻

**Review by dingo-d — APPROVED** [review]
I'm so honored to be a part of this release. After hours and hours of meetings, I'm super glad to see v3.0.0 being released.

@jrfnl it's truly an honor to work with you and learn from you 🙂 🙇🏼‍♂️

**Comment by acicovic** [comment]
Congrats for the release!

**Comment by jrfnl** [comment]
Trac ticket for WP Core: https://core.trac.wordpress.org/ticket/59161 + the actual patch: https://github.com/WordPress/wordpress-develop/pull/5047

**Comment by jrfnl** [comment]
Make post is published: https://make.wordpress.org/core/2023/08/21/wordpresscs-3-0-0-is-now-available/

**Comment by jrfnl** [comment]
Release toot: https://phpc.social/@jrf_nl/110928334999599191
Release tweet: https://twitter.com/jrf_nl/status/1693648011170095351

**Pull request merged**
