### PR TITLE
Composer: Update repo URL references

### PR DESCRIPTION
**Pull request by GaryJones**
The repo has moved organization within GitHub.

### CODE REVIEW

**Comment by dingo-d** [comment]
The travis is [green](https://travis-ci.org/WordPress/WordPress-Coding-Standards/builds/550800464), but it's stalled here. Must be the hooks issue after the repo migration.

**Comment by ntwb** [comment]
I've tidied up the legacy hooks, and tried to restart the CI tests, doesn't seem to have changed anything, instead I'll get the repo migrated from Travis CI `.org` to `.com` and see if that will help move this along.

Note: All WordPress GitHub projects have moved to `travis-ci.org` to `travis-ci.com`, see also #1750

**Comment by ntwb** [comment]
No matter what I do I'm unable to force merge this PR or restart the CI tests.

Going to close this PR and reopen a new one.

**Comment by GaryJones** [comment]
> I'll get the repo migrated from Travis CI `.org` to `.com` and see if that will help move this along.

That will mean we lose build history.

**Comment by ntwb** [comment]
> That will mean we lose build history.

The build history remains on the `.org` site at:
> https://travis-ci.org/WordPress/WordPress-Coding-Standards/builds

It also gives the repo 15 concurrent CI jobs instead of 2 or 4 which it previously had significantly speeding up CI builds

**Pull request closed without merging**
